CREATE TABLE user (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    gender TINYINT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_username (username)
);

INSERT INTO user VALUES (NULL, 'admin', '{bcrypt}$2a$10$.9BdCdkfXy6ZR0SIAGntmOKD2vYlY.44VY.jh069Fmpu4SDKXizES', 0, NOW(), NOW());
